title: Lee Docs
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://qhdrl12.github.io

aux_links:
  Template Repository: https://qhdrl12.github.io
